### ISSUE TITLE
Final crop stats in correct units

### ISSUE THREAD

**Issue by krsnapaudel** [BigDataWUR/AgML-CY-Bench#187]
Please check that all the stats you onboarded have correct units (see DATA-FORMAT.md). If not, do appropriate conversion and re-upload to Google drive. Thanks.

**Comment by ellaampy** [comment]
india and china have already been revised to follow the template. @krsnapaudel is there a standard way to name the crop statistics csv so that it is not confused with the original csvs uploaded in the Google Drive?

**Comment by krsnapaudel** [comment]
@ellaampy : for now, you can name them as `*_final.csv`. As long as there is one final csv, we will be fine.

**Comment by krsnapaudel** [comment]
The dataset should have correct units now.
