### ISSUE TITLE
document our choice of ML statistics

### ISSUE THREAD

**Issue by krsnapaudel** [BigDataWUR/AgML-CY-Bench#270]
@janet6868 : Let's document why we picked the high resolution ML crop statistics. A comparison with data from FEWSNET would be useful. Add the comparison and justification to [data sources selection document](https://github.com/BigDataWUR/AgML-CY-Bench/blob/main/data_preparation/DATA-SOURCES-SELECTION.md).

**Comment by janet6868** [comment]
Sure. I will do that. Thanks

**Comment by krsnapaudel** [comment]
@janet6868 : Could you complete this please? We will need this for ESSD dataset paper. Thanks.
