### ISSUE TITLE
nn model `predict_batch` creates more batches

### ISSUE THREAD

**Issue by krsnapaudel** [BigDataWUR/AgML-CY-Bench#271]
Predict batch was supposed to work on a batch of data. The current nn model implementation creates batches out of the data passed to `predict_batch`.

I realized that `BaseNNModel` does not implement `predict`, which it should. Then `predict_batch` can implement code for one batch.

**Comment by ronvree** [comment]
Not sure if I understand the issue, but I think the idea of `predict_batch` was to have a list of (non-tensor) input samples and have the function transform them into a batch and feed them to the network. From looking at the code I think this is what it does? `BaseNNModel` not implementing `predict` is an issue though. I think we should implement it using a call to `predict_batch` with a list containing a single sample.

**Comment by krsnapaudel** [comment]
Agree with the first part. But `predict_batch` should not need a loop to create multiple batches.

```
for i in range(0, len(X), batch_size):
                batch_end = min(i + batch_size, len(X))
                batch = X[i:batch_end]
                batch = TorchDataset.collate_fn(
                    [TorchDataset._cast_to_tensor(sample) for sample in batch]
                )
```

**Comment by ronvree** [comment]
oh yeah good point! totally agree

**Comment by aikepotze** [comment]
`predict_batch` could be changed to expect a single batch, however this would fail if the batch is too big. I agree that it would be nicer to move the logic of the creation of batches to a `predict` method and have `predict_batch` expect single batches.

**Comment by krsnapaudel** [comment]
Yes. Also @ronvree, @aikepotze, the way api is designed, we cannot really call `predict_batch` from `predict`. Predict will use a data loader, which will create batches as dict while `predict_batch` expects a list with each item a dict.
