### ISSUE TITLE
nn confusion between `best_model` and `final_model`

### ISSUE THREAD

**Issue by krsnapaudel** [BigDataWUR/AgML-CY-Bench#286]
It seems `best_model` is the best during hyperparameter search. However, it is not refitted with the entire data.

@aikepotze: could you comment on the design? Thanks.

**Comment by aikepotze** [comment]
During hyperparameter tuning, only best_settings are kept based on settings with lowest val_loss if without early stopping or best_val_loss if with early stopping.

Then, the entire fit function is called again with best_settings and the final model is fit once. If early stopping is used, a copy of the best performing model is stored at self.best_model and used in predict_batch methods. If no early stopping is used and validation fraction is set to 0, the final model is fitted with the full dataset.

The current approach is a bit counterintuitive and contains several issues, one of which is the way the best performing model is stored. Maybe it's best if we take some time to redesign it from the ground up.
