### ISSUE TITLE
a standard way to define `adm_id` (administrative region identifier)

### ISSUE THREAD

**Issue by krsnapaudel** [BigDataWUR/AgML-CY-Bench#76]
The identifier should ideally be
* indicative of larger administrative regions and country that include this region
* Commonly used so we don't define our own identifier

For EU, NUTS ID is usually a good identifier.

@ellaampy, @CarlaLimone, @mzachow, @poudelpratishtha, @Raed-Hamed Please share your thoughts.

**Comment by krsnapaudel** [comment]
I noticed that Africa data shared by Weston has 2 letter codes for country. Is it a problem if this is 2 letter code? EU data has NUTS IDs with 2 letter codes included in them. Shall we design `adm_id` to include 2-letter country code? Similarly update the data format. I added a comment to [the Google Doc](https://docs.google.com/document/d/1FnRsrWTUayza9RaWmreomQ9aaeDxJn-pgmVeKLDxtKM/edit?usp=sharing).

**Comment by ellaampy** [comment]
Regarding the country_code, both cases (2 vs 3-character) are fine and can uniquely identify each country. Considering that the EU and Africa already use the 2-character country codes, it is easier to adapt the rest to this structure. 

As for defining the adm_id, the fewer manual operations there are, the better. I believe the aim is not to uniquely identify the records in the table but to align them with the shapefile. Even in cases where we can have common names across countries, the country_code helps to decipher this similarity (unless there are cases within countries where province or district can have the same names. Is there such a case?)

Using India and China as an example, it is easier to use the names of the districts/provinces in the statistics as these are often provided in the shapefile. However, if we reconstruct an adm_id as a combination of country_code + state_code + district_code (although this will facilitate uniformity), we need to recreate a column in the shapefile to match the defined adm_id. State codes for instance are provided in the crop stats for India but not for china and none of these except the names of the units are present in the shapefiles.

**Comment by krsnapaudel** [comment]
I would favor codes or ids where possible. If codes are not present in certain types of data, we could create our mapping from codes to names.

**Comment by krsnapaudel** [comment]
The final structure is as follows:
1. Use existing ids if available and contain 2 letter country codes plus admin level codes.
2. Construct one with 2 letter country code and admin level codes. If more than one admin level is involved separate the country code and ids for different levels with a hyphen.
